parameters:
  - name: configPath
    type: string
    default: 'data/repos-config.json'
    displayName: 'Pad naar configuratiebestand'

  - name: maxParallelJobs
    type: number
    default: 0
    displayName: 'Maximum aantal parallelle jobs (0 = automatisch)'

variables:
  - name: logPath
    value: '$(Build.ArtifactStagingDirectory)/logs'

steps:
  - task: PowerShell@2
    displayName: 'Voer migratie uit'
    inputs:
      targetType: 'filePath'
      filePath: './migrate-repos.ps1'
      arguments: >
        -ConfigPath "${{ parameters.configPath }}"
        -MaxParallelJobs ${{ parameters.maxParallelJobs }}
        -LogPath "$(logPath)"
      errorActionPreference: 'stop'
      failOnStderr: false
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publiceer logs'
    condition: always()
    inputs:
      PathtoPublish: '$(logPath)'
      ArtifactName: 'migration-logs'
      publishLocation: 'Container'